project_name: weave-ai

builds:
  - <<: &build_defaults
      binary: weave-ai
      main: ./cmd/weave-ai
      ldflags:
        - -s -w -X main.Version={{ .Version }}
      env:
        - CGO_ENABLED=0
    id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
  - <<: *build_defaults
    id: darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - <<: *build_defaults
    id: windows
    goos:
      - windows

archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    id: nix
    builds: [linux, darwin]
    format: tar.gz
    files:
      - none*
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    id: windows
    builds: [windows]
    format: zip
    files:
      - none*

release:
  extra_files:
    - glob: config/release/*.yaml
  prerelease: "auto"
  header: |
    ## Changelog

    [{{.Tag}} changelog](https://github.com/weave-ai/weave-ai/blob/{{.Tag}}/CHANGELOG.md)
changelog:
  skip: true

checksum:
  extra_files:
    - glob: config/release/*.yaml

brews:
  - name: weave-ai
    tap:
      owner: weave-ai
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://weave.works"
    description: "Weave AI CLI"
    install: |
      bin.install "weave-ai"

      generate_completions_from_executable(bin/"weave-ai", "completion")
    test: |
      system "#{bin}/weave-ai --version"
