apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: tinyllama-1.1b-chat
  namespace: weave-ai
  labels:
    artifact-kind: language-model
spec:
  suspend: true # set this to false to build this LLM artifact
  interval: 10m
  url: oci://ghcr.io/weave-ai/models/tinyllama-1.1b-chat
  ref:
    tag: v0.3.0-q3ks-gguf
  layerSelector:
    mediaType: "application/vnd.cncf.flux.content.v1.tar+gzip"
    operation: copy
